AzureStorageTable/Models/ErrorViewModel.cs
using System;

namespace AzureStorageTable.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzureStorageTable/Models/Tododo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AzureStorageTable.Models
{
    public class Tododo
    {
        public string Id { get; set; }

        public string Group { get; set; }

        public bool Completed { get; set; }

        public string Item { get; set; }
    }
}

AzureStorageTable/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AzureStorageTable.Models;

namespace AzureStorageTable.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzureStorageTable/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AzureStorageTable.Models;
using AzureStorageTable.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

namespace AzureStorageTable.Controllers
{
    public class TablesController : Controller
    {
        public IActionResult Index()
        {
            var Repository = new Todo_Repository();
            List<Tododo> Todolist = new List<Tododo>();
            var entities=Repository.GetAll();
            foreach(var item in entities)
            {
                Tododo todo = new Tododo() 
                {
                    Id=item.RowKey,
                    Group=item.PartitionKey,
                    Completed=item.Completed,
                    Item=item.Item
                };

                Todolist.Add(todo);
            }

            return View(Todolist);
        }
        [HttpGet]
        public IActionResult CreateOrUpdate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateOrUpdate(Tododo todo)
        
        {
            if (!ModelState.IsValid)
            {
                return View(todo);
            }

            Entities entity = new Entities()
            {
                PartitionKey = todo.Group,
                RowKey = todo.Id,
                Completed = todo.Completed,
                Item = todo.Item
            };
            var repo = new Todo_Repository();

            repo.CreateorUpdate(entity);
            return RedirectToAction("Index");
        }

        public IActionResult GetById(string rowid, string PartionKey)
        {
            var repo = new Todo_Repository();
            Entities entity =repo.GetByRowId(rowid, PartionKey);

            Tododo todo = new Tododo()
            {
                Id = entity.RowKey,
                Group=entity.PartitionKey,
                Completed=entity.Completed,
                Item=entity.Item
            };
            return View(todo);
        }

    }
}

AzureStorageTable/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AzureStorageTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureStorageTable</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureStorageTable</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AzureStorageTable - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AzureStorageTable/Views/Tables/CreateOrUpdate.cshtml
@model AzureStorageTable.Models.Tododo

@{
    ViewData["Title"] = "CreateOrUpdate";
}

<h1>CreateOrUpdate</h1>

<h4>Tododo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Item" class="control-label"></label>
                <input asp-for="Item" class="form-control" />
                <span asp-validation-for="Item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AzureStorageTable/Views/Tables/GetById.cshtml
@model AzureStorageTable.Models.Tododo

@{
    ViewData["Title"] = "GetById";
}

<h1>GetById</h1>

<div>
    <h4>Tododo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AzureStorageTable/Views/Tables/Index.cshtml
@model IEnumerable<AzureStorageTable.Models.Tododo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="CreateOrUpdate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Completed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Completed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td>
                @Html.ActionLink("Edit","Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "GetById", new { rowid=item.Id, PartionKey=item.Group }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>